### ISSUE TITLE
"among the N browsers tested so far" -> tested in the past x months?

### ISSUE THREAD

**Issue by pde** [EFForg/panopticlick-python#20]
We currently say things like:

Your browser fingerprint __appears to be unique__ among the 808,147 tested so far.

But it would be less confusing and more informative to say

Your browser fingerprint __appears to be unique__ among the 808,147 tested in the past N months?

N=3 IIRC?

**Comment by Hainish** [comment]
This is epoched at 45 days currently, I've updated the strings to reflect this.

**Comment by Hainish** [comment]
https://github.com/EFForg/panopticlick-python/commit/6f0fce5164af1ab3e131da16dd507d447c82b9be
